---
title: "Measurement of sex and gender identity in NHANES"
author: "Jenine K Harris"
date: "9/15/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# TO CREATE ANALYTIC DATA SET, UNCOMMENT AND RUN THIS CODE CHUNK
# bring in files from online BRFSS 2015 to 2018 data
library(haven)
# #
# #
# # # 2015 data
  temp <- tempfile(fileext = ".zip")
  download.file(url  = "https://www.cdc.gov/brfss/annual_data/2015/files/LLCP2015XPT.zip", destfile = temp)
  BRFSS_2015 <- read_xpt(file = temp)
# #
# # 2016 data
 temp <- tempfile(fileext = ".zip")
 download.file(url  = "https://www.cdc.gov/brfss/annual_data/2016/files/LLCP2016XPT.zip", destfile = temp)
 BRFSS_2016 <- read_xpt(file = temp)
#
# # 2017 data
 temp <- tempfile(fileext = ".zip")
 download.file(url  = "https://www.cdc.gov/brfss/annual_data/2017/files/LLCP2017XPT.zip", destfile = temp)
 BRFSS_2017 <- read_xpt(file = temp)
#
# 2018 data
temp <- tempfile(fileext = ".zip")
download.file(url  = "https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018XPT.zip", destfile = temp)
BRFSS_2018 <- read_xpt(file = temp)

# 2019 data
temp <- tempfile(fileext = ".zip")
download.file(url  = "https://www.cdc.gov/brfss/annual_data/2019/files/LLCP2019XPT.zip", destfile = temp)
BRFSS_2019 <- read_xpt(file = temp)
#
# # select only the variables to use in the analysis (e.g. changes 300+ variables to only needed for analysis)
#
 BRFSS_2015 <- BRFSS_2015 %>%
   select(SEX, `_DRNKWEK`,TRNSGNDR)
#
 BRFSS_2016 <- BRFSS_2016 %>%
   select(SEX, `_DRNKWEK`, TRNSGNDR)
#
 BRFSS_2017 <- BRFSS_2017 %>%
   select(SEX, `_DRNKWEK`, TRNSGNDR)
#
 BRFSS_2018 <- BRFSS_2018 %>%
  select(SEX1, `_DRNKWEK`,  TRNSGNDR, `_LLCPWT`)
#
 BRFSS_2019 <- BRFSS_2019 %>%
   select(`_MICHD`, `_SEX`, EDUCA, `_BMI5CAT`, `_DRNKWK1`, EXERANY2, `_RACE`,
          `_AGE80`, `_SMOKER3`, TRNSGNDR, `_LLCPWT`)
#
# # renamed SEX1 in 2018 to SEX like all the other years
 BRFSS_2018 <- BRFSS_2018 %>%
   rename(SEX = SEX1)
 BRFSS_2019 <- BRFSS_2019 %>%
   rename(SEX = `_SEX`)
#
 # renamed AVEDRNK3 to AVEDRNK2 in 2019 like all the other years
BRFSS_2019 <- BRFSS_2019 %>%
  rename(`_DRNKWEK` = `_DRNKWK1`)

# # combine all years into 1 dataset
BRFSS_all <- rbind(BRFSS_2015, BRFSS_2016, BRFSS_2017, BRFSS_2018, BRFSS_2019)

# save BRFSS_all dataset as a .csv file so everytime i want to work with, I just read that file
# in instead of running all steps above
write.csv(BRFSS_all, file = "brfss_all_wt.csv")
```

Questions only asked of males:

IMQ070 (2015)

Questions only asked of females:

IMQ060 (2015)
IMD080 (2015)

Variables classified based on sex: 

_DRNKWK1 (all years)

